const trad = {
	english: {
		title: "WEB DEVELOPER FULL STACK FREELANCE AUDIOVISUAL",

		subtitle: "Curious, Relentless",
		coor: "CONTACT DETAILS",
		skill_title: "SKILL & QUALIFICATIONS",
		skill_1: "Team managment & communication",
		skill_2: "Curiousity & insatiability",
		skill_3: "Being able to question and change my beliefs",
		skill_4: "TECHNOLOGIES & SKILLS ",
		skill_5: "French Born & raised",
		skill_6: "PERSONNAL DETAILS",
		skill_7: "used to be a rts programer (WC3/SC2)",
		skill_8: "paleoanthropologie enthusiast",
		skill_9: "Heavy reader, American thrillers especially",
		job_1: "PROFESSIONAL EXPERIENCE",
		job_2: "DEVELOPER REACT/FRONTEND - INTERNSHIP - 2021",
		job_3: "-Setup of a BtoB internet platform handling web fluxs",
		job_4: "-Creation of scripts to allow automisation of some processes",
		job_5: "-Development of live data injecting tools",
		job_6: "-Development of overlays to display real time game informations",
		job_7: "-Organising & producing live events about VideoGames, Youtube/Twitch",
		job_8: "-Installation of studios & overall video equipment",
		job_9: "-Live realisator, assitant realisator, runner",
		job_10:
			"Took part of a few major events such as 'Gotaga Shift Race','KCX 1 & 2','Domingo*Roland Garros' and more...",
		job_11: "TECHNICAL DIRECTOR/IN CHARGE OF AUDIOVISUAL ON SITE: 2017/2020",
		job_12: "-Team management",
		job_13: "-Events production",
		job_14: "-Equipment manager",
		school_1: "-Learned programming language, PHP, JS, PYTHON",
		school_2:
			"-Learned & projects build on Laravel, ReactJS, VueJS, NestJS, NextJS, Flask, Django",
		school_3: "Learned Agile Method, handling digital projects",
		school_4:
			"-Learned Google tools web marketing, google ads, analytics... SEO & SEA",
	},
	french: {
		title: "DEVELOPPEUR WEB FULL STACK FREELANCE AUDIOVISUEL",
		subtitle: "Curieux, acharné.",
		coor: "COORDONNEES",
		skill_title: "COMPÉTENCES ET QUALIFICATIONS",
		skill_1: "Gestion d'équipe & communication",
		skill_2: "Curiosité & insatiabilité",
		skill_3: "Savoir se remettre en question",
		skill_4: "TECHNOS & COMPETENCES",
		skill_5: "Anglais Bilingue - TOEIC 970",
		skill_6: "INFOS PERSONELLES",
		skill_7: "Ancien Progamer RTS (WC3/SC2)",
		skill_8: "Passionné de Paléoanthropologie",
		skill_9: "Avide lecteur, thriller Américain en particulier",
		job_1: "EXPERIENCE PROFESIONELLES",
		job_2: "DEVELOPPER REACT/FRONTEND - STAGE - 2021",
		job_3: "-Mise en place d'une plateforme BtoB de gestion de fluxs internet",
		job_4: "-Mise en place de scripts ayant pour objectif l'automatisation de certains process de réalisation live.",
		job_5: "-Création d'outils ayant pour but d'injecter du contenu web comme habillage de live.",
		job_6: "-Création d'overlay en temps réels avec utilisation des apis (jeux) pour afficher la donnée en direct.",
		job_7: "-Organisations & production d'événements 'live' divers, jeux vidéo, youtube & twitch",
		job_8: "-Installation des plateaux & régies",
		job_9: "-Gestion de live, Réalisateur, Truquiste, Runner",
		job_10:
			"-Plusieurs gros événements, 'Gotaga Shift Race', les 'KCX' 1 & 2, 'Domingo * Roland Garros' et plein d'autres.",
		job_11:
			"DIRECTEUR TECHNIQUE EVENEMENTIEL/ RESPONSABLE AUDIOVISUEL: 2017/2020",
		job_12: "-Gestion d'équipes",
		job_13: "-Productions d'évenements",
		job_14: "-Gestion Materiel",
		school_1: "-Apprentisage des langages, PHP, JS, Python",
		school_2:
			"-Apprentisage & travaux sur les frameworks: Laravel, ReactJS, VueJS, NestJS, NextJS, Flask, Django",
		school_3:
			"-Apprentisage de la méthode agile, de la gestion de projet digital",
		school_4: "-Apprentisage des outils Google, SEO & SEA",
	},
}
export default trad
